# Generated by Django 3.1.7 on 2022-03-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='favourite',
            new_name='favourites',
        ),
    ]
