# Generated by Django 3.1.3 on 2020-12-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201202_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
