# Generated by Django 3.1.7 on 2022-03-18 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20220317_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favourites',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
