# Generated by Django 3.1.7 on 2022-03-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220318_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favourites',
        ),
    ]
