# Generated by Django 3.1.7 on 2022-03-18 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_remove_book_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favourites',
            field=models.ManyToManyField(related_name='user_fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
