# Generated by Django 3.1.3 on 2021-01-12 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favourites',
            field=models.ManyToManyField(related_name='user_fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
